name = "fastapi"
compatibility_date = "2024-04-02"

[vars]
UPSTASH_REDIS_REST_URL = "https://refined-crawdad-31435.upstash.io"
UPSTASH_REDIS_REST_TOKEN = "AXrLAAIncDEyOWIyNWQzN2Q1ODE0MzFlYmQxMGYwYmNlZTBlZWFkNXAxMzE0MzU"